# Generated by Django 5.2.17 on 2026-09-01 19:26

import certificate_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Academy logo. Recommended size: 400x400px.', null=True, upload_to='settings/', verbose_name='Logo')),
                ('academy_name_ar', models.CharField(blank=True, help_text='Academy name in Arabic.', max_length=255, null=True, verbose_name='Academy Name (Arabic)')),
                ('academy_name_en', models.CharField(blank=True, help_text='Academy name in English.', max_length=255, null=True, verbose_name='Academy Name (English)')),
                ('primary_color', models.CharField(blank=True, help_text='Primary brand color in hex (e.g. #0B2D4A).', max_length=20, null=True, verbose_name='Primary Color')),
                ('secondary_color', models.CharField(blank=True, help_text='Secondary brand color in hex (e.g. #4C9F24).', max_length=20, null=True, verbose_name='Secondary Color')),
                ('footer_text_ar', models.TextField(blank=True, help_text='Footer text in Arabic.', null=True, verbose_name='Footer Text (Arabic)')),
                ('footer_text_en', models.TextField(blank=True, help_text='Footer text in English.', null=True, verbose_name='Footer Text (English)')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Full name of the student.', max_length=255, verbose_name='Student Name')),
                ('certificate_code_1', models.CharField(help_text='Unique code for certificate 1 (e.g. FA0064).', max_length=50, unique=True, verbose_name='Certificate Code 1')),
                ('certificate_pdf_1', models.FileField(help_text='PDF file for certificate 1.', upload_to='certificates/', validators=[certificate_app.models.validate_pdf_extension], verbose_name='Certificate PDF 1')),
                ('certificate_code_2', models.CharField(blank=True, help_text='Unique code for certificate 2 (e.g. FA0065).', max_length=50, null=True, unique=True, verbose_name='Certificate Code 2')),
                ('certificate_pdf_2', models.FileField(blank=True, help_text='PDF file for certificate 2.', null=True, upload_to='certificates/', validators=[certificate_app.models.validate_pdf_extension], verbose_name='Certificate PDF 2')),
                ('certificate_code_3', models.CharField(blank=True, help_text='Unique code for certificate 3 (e.g. FA0066).', max_length=50, null=True, unique=True, verbose_name='Certificate Code 3')),
                ('certificate_pdf_3', models.FileField(blank=True, help_text='PDF file for certificate 3.', null=True, upload_to='certificates/', validators=[certificate_app.models.validate_pdf_extension], verbose_name='Certificate PDF 3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-created_at'],
            },
        ),
    ]
