# Generated by Django 5.2.17 on 2026-09-01 19:53

import certificate_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsettings',
            options={'verbose_name': 'إعدادات الموقع', 'verbose_name_plural': 'إعدادات الموقع'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-created_at'], 'verbose_name': 'شهادة المتدرب', 'verbose_name_plural': 'شهادات المتدربين'},
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='academy_name_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الأكاديمية (عربي)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='academy_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الأكاديمية (إنجليزي)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='footer_text_ar',
            field=models.TextField(blank=True, null=True, verbose_name='نص التذييل (عربي)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='footer_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='نص التذييل (إنجليزي)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='الشعار الرسمي للموقع. يفضل أن يكون بحجم 400x400 بكسل.', null=True, upload_to='settings/', verbose_name='شعار الأكاديمية'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='primary_color',
            field=models.CharField(blank=True, help_text='رمز اللون الأساسي (مثال: #0B2D4A).', max_length=20, null=True, verbose_name='اللون الأساسي'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='secondary_color',
            field=models.CharField(blank=True, help_text='رمز اللون الثانوي (مثال: #4C9F24).', max_length=20, null=True, verbose_name='اللون الثانوي'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_code_1',
            field=models.CharField(help_text='الكود الفريد للشهادة الأولى (مثال: FA0064).', max_length=50, unique=True, verbose_name='كود الشهادة 1'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_code_2',
            field=models.CharField(blank=True, help_text='الكود الفريد للشهادة الثانية (اختياري).', max_length=50, null=True, unique=True, verbose_name='كود الشهادة 2'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_code_3',
            field=models.CharField(blank=True, help_text='الكود الفريد للشهادة الثالثة (اختياري).', max_length=50, null=True, unique=True, verbose_name='كود الشهادة 3'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_pdf_1',
            field=models.FileField(help_text='ملف الـ PDF للشهادة الأولى.', upload_to='certificates/', validators=[certificate_app.models.validate_pdf_extension], verbose_name='ملف الشهادة 1 (PDF)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_pdf_2',
            field=models.FileField(blank=True, help_text='ملف الـ PDF للشهادة الثانية (اختياري).', null=True, upload_to='certificates/', validators=[certificate_app.models.validate_pdf_extension], verbose_name='ملف الشهادة 2 (PDF)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_pdf_3',
            field=models.FileField(blank=True, help_text='ملف الـ PDF للشهادة الثالثة (اختياري).', null=True, upload_to='certificates/', validators=[certificate_app.models.validate_pdf_extension], verbose_name='ملف الشهادة 3 (PDF)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student_name',
            field=models.CharField(help_text='الاسم الثلاثي أو الرباعي للطالب.', max_length=255, verbose_name='اسم الطالب'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
    ]
