# Generated by Django 5.2.17 on 2026-10-07 09:39

import certificate_app.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0003_appsettings_facebook_url_appsettings_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='qr_default_page',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = الصفحة الأولى.', verbose_name='صفحة الـ QR الافتراضية'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='qr_default_size',
            field=models.FloatField(default=0.12, help_text='نسبة من عرض الصفحة.', validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(0.5)], verbose_name='حجم الـ QR الافتراضي'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='qr_default_x',
            field=models.FloatField(default=0.8, help_text='نسبة من عرض الصفحة (0 = يسار، 1 = يمين) لأعلى يسار الـ QR.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='الموضع الأفقي الافتراضي'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='qr_default_y',
            field=models.FloatField(default=0.72, help_text='نسبة من ارتفاع الصفحة (0 = أعلى، 1 = أسفل) لأعلى يسار الـ QR.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='الموضع الرأسي الافتراضي'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_code_1',
            field=models.CharField(help_text='الكود الفريد للشهادة الأولى (مثال: FA0064).', max_length=50, unique=True, validators=[certificate_app.models.validate_certificate_code], verbose_name='كود الشهادة 1'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_code_2',
            field=models.CharField(blank=True, help_text='الكود الفريد للشهادة الثانية (اختياري).', max_length=50, null=True, unique=True, validators=[certificate_app.models.validate_certificate_code], verbose_name='كود الشهادة 2'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_code_3',
            field=models.CharField(blank=True, help_text='الكود الفريد للشهادة الثالثة (اختياري).', max_length=50, null=True, unique=True, validators=[certificate_app.models.validate_certificate_code], verbose_name='كود الشهادة 3'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_pdf_1',
            field=models.FileField(blank=True, help_text='ملف الـ PDF النهائي للشهادة الأولى.', upload_to=certificate_app.models.certificate_pdf_upload_to, validators=[certificate_app.models.validate_pdf_extension], verbose_name='ملف الشهادة 1 (PDF)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_pdf_2',
            field=models.FileField(blank=True, help_text='ملف الـ PDF للشهادة الثانية (اختياري).', null=True, upload_to=certificate_app.models.certificate_pdf_upload_to, validators=[certificate_app.models.validate_pdf_extension], verbose_name='ملف الشهادة 2 (PDF)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_pdf_3',
            field=models.FileField(blank=True, help_text='ملف الـ PDF للشهادة الثالثة (اختياري).', null=True, upload_to=certificate_app.models.certificate_pdf_upload_to, validators=[certificate_app.models.validate_pdf_extension], verbose_name='ملف الشهادة 3 (PDF)'),
        ),
        migrations.CreateModel(
            name='CertificateSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], verbose_name='رقم الشهادة')),
                ('original_pdf', models.FileField(upload_to=certificate_app.models.original_pdf_upload_to, validators=[certificate_app.models.validate_pdf_extension], verbose_name='ملف PDF الأصلي (بدون QR)')),
                ('page', models.PositiveSmallIntegerField(default=0, verbose_name='الصفحة')),
                ('x', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='الموضع الأفقي')),
                ('y', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='الموضع الرأسي')),
                ('size', models.FloatField(validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(0.5)], verbose_name='حجم الـ QR')),
                ('stamped_code', models.CharField(blank=True, max_length=50, verbose_name='الكود المطبوع')),
                ('stamped_url', models.URLField(blank=True, max_length=500, verbose_name='الرابط المطبوع')),
                ('stamped_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الطباعة')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='certificate_app.certificate', verbose_name='الشهادة')),
            ],
            options={
                'verbose_name': 'ملف شهادة أصلي',
                'verbose_name_plural': 'ملفات الشهادات الأصلية',
                'constraints': [models.UniqueConstraint(fields=('certificate', 'slot'), name='unique_certificate_source_slot')],
            },
        ),
    ]
