# Generated by Django 5.2.17 on 2026-10-07 12:15

import django.core.validators
from django.db import migrations, models


OLD_DEFAULT = {"qr_default_x": 0.80, "qr_default_y": 0.72, "qr_default_size": 0.12}
NEW_DEFAULT = {"qr_default_x": 0.0499, "qr_default_y": 0.8614, "qr_default_size": 0.0754}


def move_untouched_default(apps, schema_editor):
    """Bottom-right → bottom-left, only if the admin never changed it."""
    AppSettings = apps.get_model("certificate_app", "AppSettings")
    AppSettings.objects.filter(**OLD_DEFAULT).update(**NEW_DEFAULT)


def restore_old_default(apps, schema_editor):
    AppSettings = apps.get_model("certificate_app", "AppSettings")
    AppSettings.objects.filter(**NEW_DEFAULT).update(**OLD_DEFAULT)


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0004_certificate_qr_stamping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='qr_default_size',
            field=models.FloatField(default=0.0754, help_text='نسبة من عرض الصفحة.', validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(0.5)], verbose_name='حجم الـ QR الافتراضي'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='qr_default_x',
            field=models.FloatField(default=0.0499, help_text='نسبة من عرض الصفحة (0 = يسار، 1 = يمين) لأعلى يسار الـ QR.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='الموضع الأفقي الافتراضي'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='qr_default_y',
            field=models.FloatField(default=0.8614, help_text='نسبة من ارتفاع الصفحة (0 = أعلى، 1 = أسفل) لأعلى يسار الـ QR.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='الموضع الرأسي الافتراضي'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='qr_show_code',
            field=models.BooleanField(default=True, help_text='أوقفه إذا كان تصميم الشهادة يحتوي على الكود مكتوباً بالفعل.', verbose_name='طباعة الكود بجانب رمز QR'),
        ),
        migrations.RunPython(move_untouched_default, restore_old_default),
    ]
