# Generated by Django 5.2.17 on 2026-09-19 20:44

import academy_app.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, default='', help_text='رقم الواتساب بالصيغة الدولية بدون  مثل: 201001234567. اتركه فارغًا لإخفاء أزرار الواتساب.', max_length=32, verbose_name='رقم الواتساب')),
            ],
            options={
                'verbose_name': 'إعدادات الأكاديمية',
                'verbose_name_plural': 'إعدادات الأكاديمية',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=32, verbose_name='رقم الهاتف')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'رسالة اتصال',
                'verbose_name_plural': 'رسائل الاتصال',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', 'created_at'], name='academy_app_is_read_c411fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم الدورة (عربي)')),
                ('name_en', models.CharField(max_length=255, verbose_name='اسم الدورة (إنجليزي)')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='الرابط المختصر')),
                ('image', models.ImageField(upload_to='courses/', verbose_name='صورة الدورة')),
                ('image_alt_ar', models.CharField(blank=True, max_length=255, verbose_name='النص البديل (عربي)')),
                ('image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='النص البديل (إنجليزي)')),
                ('short_description_ar', models.TextField(blank=True, verbose_name='الوصف المختصر (عربي)')),
                ('short_description_en', models.TextField(blank=True, verbose_name='الوصف المختصر (إنجليزي)')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف الكامل (عربي)')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف الكامل (إنجليزي)')),
                ('duration_ar', models.CharField(max_length=100, verbose_name='المدة (عربي)')),
                ('duration_en', models.CharField(max_length=100, verbose_name='المدة (إنجليزي)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'دورة تدريبية',
                'verbose_name_plural': 'الدورات التدريبية',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='academy_app_is_acti_74170f_idx')],
            },
            bases=(academy_app.models.LocalizedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='صورة العرض')),
                ('image_alt_ar', models.CharField(blank=True, max_length=255, verbose_name='النص البديل للصورة (عربي)')),
                ('image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='النص البديل للصورة (إنجليزي)')),
                ('title_ar', models.CharField(blank=True, max_length=255, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='العنوان (إنجليزي)')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف (عربي)')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف (إنجليزي)')),
                ('button_text_ar', models.CharField(blank=True, max_length=100, verbose_name='نص الزر (عربي)')),
                ('button_text_en', models.CharField(blank=True, max_length=100, verbose_name='نص الزر (إنجليزي)')),
                ('button_url', models.URLField(blank=True, verbose_name='رابط الزر')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'شريحة العرض الرئيسي',
                'verbose_name_plural': 'شرائح العرض الرئيسي',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='academy_app_is_acti_40fecc_idx')],
            },
            bases=(academy_app.models.LocalizedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/', verbose_name='صورة التقييم')),
                ('image_alt_ar', models.CharField(blank=True, max_length=255, verbose_name='النص البديل (عربي)')),
                ('image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='النص البديل (إنجليزي)')),
                ('student_name_ar', models.CharField(blank=True, max_length=255, verbose_name='اسم الطالب (عربي)')),
                ('student_name_en', models.CharField(blank=True, max_length=255, verbose_name='اسم الطالب (إنجليزي)')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف (عربي)')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف (إنجليزي)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'تقييم الطالب',
                'verbose_name_plural': 'تقييمات الطلاب',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='academy_app_is_acti_9a5e4f_idx')],
            },
            bases=(academy_app.models.LocalizedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم الخدمة (عربي)')),
                ('name_en', models.CharField(max_length=255, verbose_name='اسم الخدمة (إنجليزي)')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='الرابط المختصر')),
                ('image', models.ImageField(upload_to='services/', verbose_name='صورة الخدمة')),
                ('image_alt_ar', models.CharField(blank=True, max_length=255, verbose_name='النص البديل (عربي)')),
                ('image_alt_en', models.CharField(blank=True, max_length=255, verbose_name='النص البديل (إنجليزي)')),
                ('short_description_ar', models.TextField(blank=True, verbose_name='الوصف المختصر (عربي)')),
                ('short_description_en', models.TextField(blank=True, verbose_name='الوصف المختصر (إنجليزي)')),
                ('content_ar', models.TextField(blank=True, verbose_name='المحتوى (عربي)')),
                ('content_en', models.TextField(blank=True, verbose_name='المحتوى (إنجليزي)')),
                ('external_url', models.URLField(blank=True, verbose_name='رابط خارجي')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='academy_app_is_acti_926663_idx')],
            },
            bases=(academy_app.models.LocalizedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(blank=True, max_length=255, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='العنوان (إنجليزي)')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف (عربي)')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف (إنجليزي)')),
                ('video_file', models.FileField(help_text='يدعم mp4 أو webm بحجم أقصاه 15 م.ب', upload_to='courses/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'], message='اسم الملف ليس مدعومًا. استخدم mp4 أو webm.'), academy_app.models.validate_video_size], verbose_name='ملف الفيديو')),
                ('thumbnail', models.ImageField(blank=True, upload_to='courses/video_thumbnails/', verbose_name='صورة مصغرة')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='academy_app.course', verbose_name='الدورة')),
            ],
            options={
                'verbose_name': 'فيديو الدورة',
                'verbose_name_plural': 'فيديوهات الدورات',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['course', 'is_active', 'display_order'], name='academy_app_course__52597a_idx')],
            },
            bases=(academy_app.models.LocalizedMixin, models.Model),
        ),
    ]
